name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -project 'IMC.xcodeproj' -scheme 'IMC' -destination 'platform=iOS Simulator,name=iPhone 11 Pro’ test
    - name: Build app
      run: xcodebuild -project 'IMC.xcodeproj' -scheme 'IMC' -destination 'platform=iOS Simulator,name=iPhone 11 Pro’ -configuration Release build CODE_SIGNING_ALLOWED=NO
